#!/usr/bin/python


#flashON

import time
import serial
import commands

arduino = serial.Serial('/dev/ttyACM0', 9600)

print("Hablando con Leonardo")

while True:
    comando = 'H' #Input
    arduino.write(comando) #Mandar un comando hacia Arduino
    if comando == 'H':
        print('LED ENCENDIDO')
    elif comando == 'L':
        print('LED APAGADO')
    break
arduino.close() #Finalizamos la comunicacion

time.sleep(4)
output=commands.getoutput('sh /usr/bin/foto')

